### ISSUE TITLE
Rename of library Modelica_EnergyStorages

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica_EnergyStorages#7]
**Reported by dietmarw on 27 Jun 2013 09:09 UTC**
Speaking of energy storage**s** seems to be as wrong as speaking of "information**s**". I got this from a native speaker and other native speakers might want comment on this too.

At the same time, and as long as it's not placed within the MSL under `Modelica.Electrical`, it should be called `ElectricalEnergyStorage` library just to avoid confusions with other energy storage systems.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1184

**Comment by modelica-trac-importer** [comment]
**Comment by mtiller on 27 Jun 2013 12:11 UTC**
This is true.  I would not say "storages".

**Comment by modelica-trac-importer** [comment]
**Modified by ahaumer on 30 Jul 2013 10:16 UTC**

**Comment by dietmarw** [comment]
@christiankral Could we once and for all clean this up. Since we currently moving the development under the github.com/modelica account now would be the time to sort this out.

I strongly suggest to rename the library and the repository to `ElectricalEnergyStorage` as suggested earlier. Reasons:
 1. as confirmed by @AHaumer there is no active development (even planed) on this project. So suggesting it was fit for MSL inclusion is simply misinforming. So drop the `Modelica_`
 2. the library is for electrical energy storage only, so better make this clear in the name
 3. the trailing "s" is simply a mistake and makes no sense (also confirmed by native speakers)

**Comment by christiankral** [comment]
Yes, please go ahead and rename the library to *ElectricalEnergyStorage*.

Thanks,
Christian
